export enum Icons {
  // Navigation & Menu
  Home = 'mdi-home',
  Menu = 'mdi-menu',
  Close = 'mdi-close',
  DotsVertical = 'mdi-dots-vertical',
  DotsHorizontal = 'mdi-dots-horizontal',
  ChevronUp = 'mdi-chevron-up',
  ChevronDown = 'mdi-chevron-down',
  ChevronLeft = 'mdi-chevron-left',
  ChevronRight = 'mdi-chevron-right',
  ArrowLeft = 'mdi-arrow-left',
  ArrowRight = 'mdi-arrow-right',
  ArrowUp = 'mdi-arrow-up',
  ArrowDown = 'mdi-arrow-down',
  UnfoldMore = 'mdi-unfold-more-horizontal',
  ExitRun = 'mdi-exit-run',

  // Actions
  Plus = 'mdi-plus',
  Minus = 'mdi-minus',
  Delete = 'mdi-delete',
  DeleteOutline = 'mdi-delete-outline',
  Edit = 'mdi-pencil',
  PencilPlus = 'mdi-pencil-plus',
  Search = 'mdi-magnify',
  Refresh = 'mdi-refresh',
  Sync = 'mdi-sync',
  Check = 'mdi-check',
  CheckAll = 'mdi-check-all',
  CheckCircle = 'mdi-check-circle',
  Cancel = 'mdi-cancel',
  CloseCircle = 'mdi-close-circle',
  Play = 'mdi-play',
  PlayCircle = 'mdi-play-circle',
  Pause = 'mdi-pause',
  Stop = 'mdi-stop',
  Send = 'mdi-send',
  Share = 'mdi-share-variant',
  Copy = 'mdi-content-copy',
  Paste = 'mdi-content-paste',
  Undo = 'mdi-undo',
  Redo = 'mdi-redo',
  CursorClick = 'mdi-cursor-default-click',

  // Status & Alerts
  Alert = 'mdi-alert',
  AlertCircle = 'mdi-alert-circle',
  AlertOctagon = 'mdi-alert-octagon',
  Info = 'mdi-information',
  InfoOutline = 'mdi-information-outline',
  Warning = 'mdi-alert-circle',
  Error = 'mdi-alert-octagon',
  HelpCircle = 'mdi-help-circle',
  HelpCircleOutline = 'mdi-help-circle-outline',
  Circle = 'mdi-circle',
  CircleMedium = 'mdi-circle-medium',
  CircleOutline = 'mdi-circle-outline',
  Hexagon = 'mdi-hexagon',
  Puzzle = 'mdi-puzzle',

  // Account & Users
  Account = 'mdi-account',
  AccountCircle = 'mdi-account-circle',
  AccountOutline = 'mdi-account-outline',
  AccountPlus = 'mdi-account-plus',
  AccountMinus = 'mdi-account-minus',
  AccountCheck = 'mdi-account-check',
  AccountOff = 'mdi-account-off',
  AccountKey = 'mdi-account-key',
  AccountMultiple = 'mdi-account-multiple',
  AccountGroup = 'mdi-account-group',
  AccountCog = 'mdi-account-cog',
  ShieldAccount = 'mdi-shield-account',

  // Security & Lock
  Lock = 'mdi-lock',
  LockOpen = 'mdi-lock-open',
  LockCheck = 'mdi-lock-check',
  LockReset = 'mdi-lock-reset',
  LockOutline = 'mdi-lock-outline',
  Shield = 'mdi-shield',
  ShieldCheck = 'mdi-shield-check',
  ShieldLock = 'mdi-shield-lock',
  ShieldKey = 'mdi-shield-key',
  ShieldCrown = 'mdi-shield-crown',
  Key = 'mdi-key',
  KeyVariant = 'mdi-key-variant',

  // Visibility
  Eye = 'mdi-eye',
  EyeOff = 'mdi-eye-off',
  EyeOutline = 'mdi-eye-outline',

  // Settings & Tools
  Settings = 'mdi-cog',
  Cog = 'mdi-cog',
  CogOutline = 'mdi-cog-outline',
  Wrench = 'mdi-wrench',
  Tune = 'mdi-tune',
  Palette = 'mdi-palette',
  FormatPaint = 'mdi-format-paint',
  Api = 'mdi-api',
  Console = 'mdi-console',
  CodeBraces = 'mdi-code-braces',
  CodeTags = 'mdi-code-tags',
  Database = 'mdi-database',
  Robot = 'mdi-robot',

  // Auth & Login
  Logout = 'mdi-logout',
  Login = 'mdi-login',
  Fingerprint = 'mdi-fingerprint',
  TwoFactorAuth = 'mdi-two-factor-authentication',

  // Date & Time
  Calendar = 'mdi-calendar',
  CalendarRange = 'mdi-calendar-range',
  CalendarCheck = 'mdi-calendar-check',
  Clock = 'mdi-clock',
  ClockOutline = 'mdi-clock-outline',
  ClockCheck = 'mdi-clock-check',
  History = 'mdi-history',
  Timer = 'mdi-timer',
  TimerSand = 'mdi-timer-sand',

  // Communication
  Email = 'mdi-email',
  EmailOutline = 'mdi-email-outline',
  EmailOpen = 'mdi-email-open',
  EmailPlus = 'mdi-email-plus',
  At = 'mdi-at',
  Phone = 'mdi-phone',
  PhoneOutline = 'mdi-phone-outline',
  PhoneInTalk = 'mdi-phone-in-talk',
  Chat = 'mdi-chat',
  ChatOutline = 'mdi-chat-outline',
  ChatProcessing = 'mdi-chat-processing',
  Message = 'mdi-message',
  MessageOutline = 'mdi-message-outline',
  MessageText = 'mdi-message-text',
  MessageReply = 'mdi-message-reply',
  Comment = 'mdi-comment',
  CommentOutline = 'mdi-comment-outline',
  CommentText = 'mdi-comment-text',
  Forum = 'mdi-forum',
  Bell = 'mdi-bell',
  BellOutline = 'mdi-bell-outline',
  BellRing = 'mdi-bell-ring',
  BellOff = 'mdi-bell-off',

  // Favorites & Rating
  Star = 'mdi-star',
  StarOutline = 'mdi-star-outline',
  StarHalf = 'mdi-star-half-full',
  Heart = 'mdi-heart',
  HeartOutline = 'mdi-heart-outline',
  ThumbUp = 'mdi-thumb-up',
  ThumbDown = 'mdi-thumb-down',
  ThumbUpOutline = 'mdi-thumb-up-outline',
  EmoticonHappy = 'mdi-emoticon-happy',
  EmoticonOutline = 'mdi-emoticon-outline',
  EmoticonSad = 'mdi-emoticon-sad-outline',

  // Files & Documents
  File = 'mdi-file',
  FileOutline = 'mdi-file-outline',
  FileDocument = 'mdi-file-document',
  FileDocumentOutline = 'mdi-file-document-outline',
  FileDocumentPlus = 'mdi-file-document-plus',
  FileSearch = 'mdi-file-search-outline',
  FileUpload = 'mdi-file-upload',
  FileDownload = 'mdi-file-download',
  FilePdf = 'mdi-file-pdf-box',
  FileImage = 'mdi-file-image',
  Folder = 'mdi-folder',
  FolderOpen = 'mdi-folder-open',
  FolderPlus = 'mdi-folder-plus',
  FolderOutline = 'mdi-folder-outline',
  Paperclip = 'mdi-paperclip',
  Attachment = 'mdi-attachment',

  // Upload & Download
  Upload = 'mdi-upload',
  Download = 'mdi-download',
  CloudUpload = 'mdi-cloud-upload',
  CloudDownload = 'mdi-cloud-download',
  Cloud = 'mdi-cloud',
  CloudOutline = 'mdi-cloud-outline',

  // Filter & Sort
  Filter = 'mdi-filter',
  FilterOutline = 'mdi-filter-outline',
  FilterVariant = 'mdi-filter-variant',
  Sort = 'mdi-sort',
  SortAscending = 'mdi-sort-ascending',
  SortDescending = 'mdi-sort-descending',

  // Shopping & E-commerce
  Cart = 'mdi-cart',
  CartOutline = 'mdi-cart-outline',
  CartPlus = 'mdi-cart-plus',
  CartCheck = 'mdi-cart-check',
  CartRemove = 'mdi-cart-remove',
  Store = 'mdi-store',
  StoreOutline = 'mdi-store-outline',
  Tag = 'mdi-tag',
  TagOutline = 'mdi-tag-outline',
  TagMultiple = 'mdi-tag-multiple',
  Sale = 'mdi-sale',
  Percent = 'mdi-percent',
  Gift = 'mdi-gift',
  GiftOutline = 'mdi-gift-outline',
  Package = 'mdi-package',
  PackageVariant = 'mdi-package-variant',
  Ticket = 'mdi-ticket',
  TicketPercent = 'mdi-ticket-percent',
  Barcode = 'mdi-barcode',

  // Financial
  Cash = 'mdi-cash',
  CashMultiple = 'mdi-cash-multiple',
  CashCheck = 'mdi-cash-check',
  CashMinus = 'mdi-cash-minus',
  CashPlus = 'mdi-cash-plus',
  CashRefund = 'mdi-cash-refund',
  CreditCard = 'mdi-credit-card',
  CreditCardOutline = 'mdi-credit-card-outline',
  CreditCardCheck = 'mdi-credit-card-check',
  CurrencyUsd = 'mdi-currency-usd',
  CurrencyEur = 'mdi-currency-eur',
  Bank = 'mdi-bank',
  Wallet = 'mdi-wallet',
  WalletOutline = 'mdi-wallet-outline',
  Receipt = 'mdi-receipt',
  Invoice = 'mdi-invoice-text',

  // Charts & Analytics
  ChartLine = 'mdi-chart-line',
  ChartBar = 'mdi-chart-bar',
  ChartPie = 'mdi-chart-pie',
  ChartDonut = 'mdi-chart-donut',
  ChartAreaspline = 'mdi-chart-areaspline',
  ChartBox = 'mdi-chart-box',
  Poll = 'mdi-poll',
  TrendingUp = 'mdi-trending-up',
  TrendingDown = 'mdi-trending-down',
  Finance = 'mdi-finance',
  GoogleAnalytics = 'mdi-google-analytics',

  // Dashboard & Views
  ViewDashboard = 'mdi-view-dashboard',
  ViewGrid = 'mdi-view-grid',
  ViewList = 'mdi-view-list',
  ViewModule = 'mdi-view-module',
  ViewColumn = 'mdi-view-column',
  ViewAgenda = 'mdi-view-agenda',
  Apps = 'mdi-apps',
  Widgets = 'mdi-widgets',
  LayoutGrid = 'mdi-view-grid-plus',

  // Devices & Tech
  Laptop = 'mdi-laptop',
  Desktop = 'mdi-desktop-mac',
  Monitor = 'mdi-monitor',
  Tablet = 'mdi-tablet',
  Cellphone = 'mdi-cellphone',
  Television = 'mdi-television',
  Headphones = 'mdi-headphones',
  Camera = 'mdi-camera',
  Video = 'mdi-video',
  VideoOutline = 'mdi-video-outline',
  Microphone = 'mdi-microphone',
  VolumeHigh = 'mdi-volume-high',
  VolumeMute = 'mdi-volume-mute',
  Printer = 'mdi-printer',
  Memory = 'mdi-memory',
  Cpu = 'mdi-cpu-64-bit',
  Server = 'mdi-server',
  Wifi = 'mdi-wifi',
  Bluetooth = 'mdi-bluetooth',
  Usb = 'mdi-usb',

  // Location & Travel
  MapMarker = 'mdi-map-marker',
  MapMarkerOutline = 'mdi-map-marker-outline',
  MapMarkerRadius = 'mdi-map-marker-radius',
  Map = 'mdi-map',
  MapOutline = 'mdi-map-outline',
  Compass = 'mdi-compass',
  Navigation = 'mdi-navigation',
  Earth = 'mdi-earth',
  Globe = 'mdi-globe-model',
  Airplane = 'mdi-airplane',
  Car = 'mdi-car',
  Train = 'mdi-train',
  Bus = 'mdi-bus',
  Truck = 'mdi-truck',
  TruckDelivery = 'mdi-truck-delivery',
  TruckFast = 'mdi-truck-fast',
  Bike = 'mdi-bike',
  Walk = 'mdi-walk',

  // Weather & Nature
  WeatherSunny = 'mdi-weather-sunny',
  WeatherNight = 'mdi-weather-night',
  WeatherCloudy = 'mdi-weather-cloudy',
  WeatherRainy = 'mdi-weather-rainy',
  WeatherSnowy = 'mdi-weather-snowy',
  WhiteBalanceSunny = 'mdi-white-balance-sunny',
  MoonWaning = 'mdi-moon-waning-crescent',
  Brightness = 'mdi-brightness-6',
  Lightbulb = 'mdi-lightbulb',
  LightbulbOutline = 'mdi-lightbulb-outline',
  Fire = 'mdi-fire',
  Water = 'mdi-water',
  Leaf = 'mdi-leaf',
  Tree = 'mdi-tree',
  Flower = 'mdi-flower',

  // Social Media
  Facebook = 'mdi-facebook',
  Twitter = 'mdi-twitter',
  Instagram = 'mdi-instagram',
  LinkedIn = 'mdi-linkedin',
  Youtube = 'mdi-youtube',
  Github = 'mdi-github',
  Google = 'mdi-google',
  Apple = 'mdi-apple',
  Microsoft = 'mdi-microsoft',
  Slack = 'mdi-slack',
  Discord = 'mdi-discord',
  Telegram = 'mdi-telegram',
  Whatsapp = 'mdi-whatsapp',
  Reddit = 'mdi-reddit',
  Pinterest = 'mdi-pinterest',
  Dribbble = 'mdi-dribbble',
  Spotify = 'mdi-spotify',
  Twitch = 'mdi-twitch',

  // Web & Links
  Web = 'mdi-web',
  Link = 'mdi-link',
  LinkVariant = 'mdi-link-variant',
  LinkOff = 'mdi-link-off',
  OpenInNew = 'mdi-open-in-new',
  Launch = 'mdi-launch',
  Domain = 'mdi-domain',
  Dns = 'mdi-dns',

  // Business & Office
  Briefcase = 'mdi-briefcase',
  BriefcaseOutline = 'mdi-briefcase-outline',
  OfficeBuilding = 'mdi-office-building',
  OfficeBuildingOutline = 'mdi-office-building-outline',
  Factory = 'mdi-factory',
  Rocket = 'mdi-rocket',
  RocketLaunch = 'mdi-rocket-launch',
  Bullhorn = 'mdi-bullhorn',
  Target = 'mdi-target',
  Trophy = 'mdi-trophy',
  Medal = 'mdi-medal',
  Crown = 'mdi-crown',
  Handshake = 'mdi-handshake',
  Chart = 'mdi-chart-timeline-variant',
  Presentation = 'mdi-presentation',
  Clipboard = 'mdi-clipboard',
  ClipboardText = 'mdi-clipboard-text',
  ClipboardCheck = 'mdi-clipboard-check',
  ClipboardList = 'mdi-clipboard-list',
  Notebook = 'mdi-notebook',
  BookOpen = 'mdi-book-open',
  BookOutline = 'mdi-book-outline',
  School = 'mdi-school',
  GraduationCap = 'mdi-school',
  Certificate = 'mdi-certificate',

  // Image & Media
  Image = 'mdi-image',
  ImageOutline = 'mdi-image-outline',
  ImageMultiple = 'mdi-image-multiple',
  ImagePlus = 'mdi-image-plus',
  ImageEdit = 'mdi-image-edit',
  Panorama = 'mdi-panorama',
  Movie = 'mdi-movie',
  MovieOpen = 'mdi-movie-open',
  Music = 'mdi-music',
  MusicNote = 'mdi-music-note',
  Playlist = 'mdi-playlist-music',
  Album = 'mdi-album',
  Gamepad = 'mdi-gamepad-variant',
  Controller = 'mdi-controller',

  // Text & Format
  FormatBold = 'mdi-format-bold',
  FormatItalic = 'mdi-format-italic',
  FormatUnderline = 'mdi-format-underline',
  FormatAlignLeft = 'mdi-format-align-left',
  FormatAlignCenter = 'mdi-format-align-center',
  FormatAlignRight = 'mdi-format-align-right',
  FormatListBulleted = 'mdi-format-list-bulleted',
  FormatListNumbered = 'mdi-format-list-numbered',
  FormatQuote = 'mdi-format-quote-close',
  FormatSize = 'mdi-format-size',
  FormatColorFill = 'mdi-format-color-fill',
  FormatColorText = 'mdi-format-color-text',
  Heading = 'mdi-format-header-1',
  TextBox = 'mdi-text-box',
  TextBoxOutline = 'mdi-text-box-outline',

  // Misc UI
  QrCode = 'mdi-qrcode',
  Scan = 'mdi-qrcode-scan',
  Bookmark = 'mdi-bookmark',
  BookmarkOutline = 'mdi-bookmark-outline',
  Flag = 'mdi-flag',
  FlagOutline = 'mdi-flag-outline',
  Pin = 'mdi-pin',
  PinOutline = 'mdi-pin-outline',
  Label = 'mdi-label',
  LabelOutline = 'mdi-label-outline',
  Flash = 'mdi-flash',
  FlashOutline = 'mdi-flash-outline',
  Bolt = 'mdi-lightning-bolt',
  BoltOutline = 'mdi-lightning-bolt-outline',
  Power = 'mdi-power',
  PowerPlug = 'mdi-power-plug',
  Battery = 'mdi-battery',
  BatteryCharging = 'mdi-battery-charging',
  Magnet = 'mdi-magnet',
  Infinity = 'mdi-infinity',
  Atom = 'mdi-atom',
  Led = 'mdi-led-on',
  Box = 'mdi-checkbox-marked',
  BoxOutline = 'mdi-checkbox-blank-outline',
  MinusCircle = 'mdi-minus-circle',

  // Tables & Data
  Table = 'mdi-table',
  TableLarge = 'mdi-table-large',
  TableEdit = 'mdi-table-edit',
  TablePlus = 'mdi-table-plus',
  TableSearch = 'mdi-table-search',
  TableExport = 'mdi-table-arrow-right',
  Grid = 'mdi-grid',
  GridLarge = 'mdi-grid-large',

  // Code & Development
  Code = 'mdi-code-tags',
  CodeJson = 'mdi-code-json',
  Bug = 'mdi-bug',
  BugOutline = 'mdi-bug-outline',
  TestTube = 'mdi-test-tube',
  Flask = 'mdi-flask',
  SourceBranch = 'mdi-source-branch',
  SourceMerge = 'mdi-source-merge',
  SourcePull = 'mdi-source-pull',
  Git = 'mdi-git',
  Terminal = 'mdi-console-line',

  // Arrows & Directions
  ArrowExpand = 'mdi-arrow-expand',
  ArrowCollapse = 'mdi-arrow-collapse',
  ArrowUpBold = 'mdi-arrow-up-bold',
  ArrowDownBold = 'mdi-arrow-down-bold',
  SwapHorizontal = 'mdi-swap-horizontal',
  SwapVertical = 'mdi-swap-vertical',
  Drag = 'mdi-drag',
  DragHorizontal = 'mdi-drag-horizontal',
  DragVertical = 'mdi-drag-vertical',
  Resize = 'mdi-resize',
  FullScreen = 'mdi-fullscreen',
  FullScreenExit = 'mdi-fullscreen-exit',

  // Time-related actions
  Alarm = 'mdi-alarm',
  AlarmPlus = 'mdi-alarm-plus',
  Stopwatch = 'mdi-timer',
  Hourglass = 'mdi-timer-sand',

  // Additional common icons
  Information = 'mdi-information',
  InformationOutline = 'mdi-information-outline',
  QuoteOpen = 'mdi-format-quote-open',
  QuoteClose = 'mdi-format-quote-close',
  Restore = 'mdi-restore',
  ContentSave = 'mdi-content-save',
  ContentSaveOutline = 'mdi-content-save-outline',
  Export = 'mdi-export',
  Import = 'mdi-import',
  Print = 'mdi-printer',
  ZoomIn = 'mdi-magnify-plus',
  ZoomOut = 'mdi-magnify-minus',
  Minus2 = 'mdi-minus',
  Square = 'mdi-square',
  SquareOutline = 'mdi-square-outline',
  RadioboxMarked = 'mdi-radiobox-marked',
  RadioboxBlank = 'mdi-radiobox-blank',

  // Forms & Input
  FormSelect = 'mdi-form-select',
  FormTextbox = 'mdi-form-textbox',

  // Cards
  CardOutline = 'mdi-card-outline',
  CardText = 'mdi-card-text',

  // Windows & Dialogs
  WindowOpen = 'mdi-window-open',
  WindowMaximize = 'mdi-window-maximize',

  // Content & Posts
  Post = 'mdi-post',
  NewspaperVariant = 'mdi-newspaper-variant',

  // Misc missing icons
  ShieldStarOutline = 'mdi-shield-star-outline',
  Ungroup = 'mdi-ungroup',
  DatabaseOff = 'mdi-database-off',
  Keyboard = 'mdi-keyboard',
  MessageTextOutline = 'mdi-message-text-outline',
  MessageImage = 'mdi-message-image',
  Select = 'mdi-select',
  FolderMultipleOutline = 'mdi-folder-multiple-outline',
  CommentMultiple = 'mdi-comment-multiple',
  CommentAlert = 'mdi-comment-alert',
  CommentQuote = 'mdi-comment-quote',
  FileAlert = 'mdi-file-alert',
  ServerOff = 'mdi-server-off',
  Tools = 'mdi-tools',
  ViewHeadline = 'mdi-view-headline',
  ViewCarousel = 'mdi-view-carousel',
  ArrowDecision = 'mdi-arrow-decision',
  FeatureSearch = 'mdi-feature-search',
  Storefront = 'mdi-storefront',
  Bitcoin = 'mdi-bitcoin',
  BankTransfer = 'mdi-bank-transfer',
  Headset = 'mdi-headset'
}
